apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: legisai-platform
resources:
- ../../base
images:
- name: webapp:1.0.0
  newName: legisaiacrdev.azurecr.io/webapp
  newTag: 0a4ed3c
