apiVersion: v1
kind: Service
metadata:
    name: webapp-service
spec:
    type: ClusterIP
    selector:
        app: webapp
    ports:
        - protocol: TCP
          port: 9020
          targetPort: 9020
